name: TerraformAzureDeploy
on:
  push:
    branches: 
    - tf-validation-module
env:
  ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Generate Azure oAuth Token
        #run: curl -X POST -d 'grant_type=client_credentials&client_id=[APP_ID]&client_secret=[PASSWORD]&resource=https%3A%2F%2Fmanagement.azure.com%2F' https://login.microsoftonline.com/[TENANT_ID]/oauth2/token
        run: |
          response=$(curl -X POST -d "grant_type=client_credentials&client_id=${{ secrets.CLIENT_ID }}&client_secret=${{ secrets.CLIENT_SECRET }}&resource=https%3A%2F%2Fmanagement.azure.com%2F" https://login.microsoftonline.com/${{ secrets.TENANT_ID }}/oauth2/token)         
          echo "response from curl= $response"  
      
      - name: Terraform Init
        run: terraform init
      
      ##### Try to fix later
      #- name: Terraform Format
      #  run: terraform fmt -check    
      
      - name: Terraform Plan
        run: terraform plan
      
      - name: Terraform Apply
        run: terraform apply --auto-approve